---
name: HTTP-Server-Simple-Er
version: v0.0.4
author:
  - 'Eric Wilhelm @ <ewilhelm at cpan dot org>'
abstract: lightweight server and interface
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=HTTP-Server-Simple-Er
  homepage: http://scratchcomputing.com/
  license: http://dev.perl.org/licenses/
  repository: http://svn.scratchcomputing.com/HTTP-Server-Simple-Er/trunk
build_requires:
  Module::Build: 0.26
  Test::More: 0
requires:
  Class::Accessor::Classy: v0.9.0
  HTTP::Server::Simple: 0.27
  URI::Escape: 0
configure_requires:
  Module::Build: 0.3401
provides:
  HTTP::Server::Simple::Er:
    file: lib/HTTP/Server/Simple/Er.pm
    version: v0.0.4
generated_by: Module::Build version 0.3401
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
